name: blog_application
description: A new Flutter project.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.1.3
  cached_network_image: 3.1.0+1
  cloud_firestore: 2.5.4
  equatable: 1.2.6
  firebase_auth: 3.2.0
  firebase_core: 1.10.0
  firebase_storage: 10.1.0
  font_awesome_flutter: 8.11.0
  google_fonts: 2.1.0
  google_sign_in: 4.5.9
  image_picker: 0.8.4+4
  intl: 0.17.0
  json_path: 0.2.1
  json_serializable: 4.1.4
  mime_type: 1.0.0
  page_transition: 2.0.4
  rxdart: 0.26.0
  sign_in_with_apple: 3.3.0
  timeago: 3.1.0
  url_launcher: 6.0.15
  flow_builder: ^0.0.6
  provider: ^5.0.0
  collection: ^1.15.0


dev_dependencies:
  build_runner: 2.1.5
  built_value_generator: 8.1.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
